### ISSUE TITLE
WITH-UNLOCKED-PACKAGES on an unlocked package should be a no-op

### ISSUE THREAD

**Issue by phoe** [yitzchak/trivial-package-locks#1]
https://github.com/yitzchak/trivial-package-locks/blob/6147d7b67b4dc04303add928eb531bf4cb83b5a9/code/locks.lisp#L50-L59

If a package is unlocked once control reaches this form, it should probably stay unlocked once control leaves it. `with-unlocked-packages` will unconditionally lock it though.

A solution is to memorize the locked packages and iterate through them in the `unwind-protect`'s cleanup clause.

**Comment by phoe** [comment]
Wait, I badly misread the code - it already does what I described. Sorry!

**Comment by yitzchak** [comment]
No worries, mate! Thanks for taking a look.
