### ISSUE TITLE
Tests should depend on the package under test

### ISSUE THREAD

**Issue by phoe** [yitzchak/trivial-package-locks#4]
https://github.com/yitzchak/trivial-package-locks/blob/3e66d93edd4158c295826deb675367fd7f32fe34/trivial-package-locks.asd#L21

This causes a Quicklisp failure: http://report.quicklisp.org/2021-12-29/failure-report/trivial-package-locks.html

**Comment by yitzchak** [comment]
Thanks @phoe, fixed.
